packages:
  - homepage
  - packages/agent
  - packages/city
  - packages/plugin
  - packages/workspace
  - app/desktop
  - packages/workspace-adapters/*
  - packages/federation
  - packages/services
  - packages/plugins
  - packages/sandboxes/*
  - packages/type
  - app/cli
  - app/fedman
  - packages/ui
  - packages/databases/*
  - templates/*
  - templates/agent/*
  - examples/*

allowBuilds:
  better-sqlite3: true
  electron: true
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true
  sharp: true
  workerd: true

onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - node-pty
