/**
 * Chat Plugin 的结构化配置协议。
 *
 * 关键点（中文）
 * - Zod Schema 是内建 Chat 行为配置与 Resource 配置的唯一源码。
 * - Plugin config 只描述 queue 行为，完整渠道配置由独立 Resource Item 承载。
 * - `readOnly` 字段由 Resource Resolver 写入，`writeOnly` 字段由 CLI 安全采集和脱敏。
 */

import type { JsonObject } from "@downcity/agent";
import { z } from "zod";
import { resolveChatChannelBotInfo } from "@/chat/channels/BotInfoProvider.js";
import type { ChatPluginResource } from "@/chat/types/ChatPluginResource.js";

const resource_id_schema = z.string()
  .trim()
  .min(1)
  .max(80)
  .regex(/^[a-z0-9][a-z0-9_-]*$/u)
  .meta({
    title: "Resource ID",
    description: "Stable Resource ID generated by City.",
    readOnly: true,
  });

const resource_name_schema = z.string()
  .trim()
  .min(1)
  .meta({
    title: "Name",
    description: "Display name written by the Resource Resolver.",
    readOnly: true,
  });

const secret_schema = z.string()
  .trim()
  .min(1)
  .meta({ writeOnly: true });

/** Telegram Resource 完整配置 Schema。 */
const telegram_resource_schema = z.object({
  id: resource_id_schema,
  type: z.literal("telegram").meta({ title: "Type" }),
  name: resource_name_schema,
  bot_token: secret_schema.meta({
    title: "Bot Token",
    description: "Telegram Bot API Token.",
    writeOnly: true,
  }),
  username: z.string().trim().min(1).optional().meta({
    title: "Username",
    description: "Telegram username written by the Resource Resolver.",
    readOnly: true,
  }),
  bot_user_id: z.string().trim().min(1).optional().meta({
    title: "Bot User ID",
    description: "Telegram Bot user ID written by the Resource Resolver.",
    readOnly: true,
  }),
}).strict().meta({
  title: "Telegram",
  description: "Telegram Bot Resource.",
});

/** Feishu / Lark Resource 完整配置 Schema。 */
const feishu_resource_schema = z.object({
  id: resource_id_schema,
  type: z.literal("feishu").meta({ title: "Type" }),
  name: resource_name_schema,
  app_id: z.string().trim().min(1).meta({
    title: "App ID",
    description: "Feishu or Lark App ID.",
  }),
  app_secret: secret_schema.meta({
    title: "App Secret",
    description: "Feishu or Lark App Secret.",
    writeOnly: true,
  }),
  domain: z.url().optional().meta({
    title: "Open API Domain",
    description: "Optional Feishu or Lark Open API domain.",
  }),
  identity: z.string().trim().min(1).optional().meta({
    title: "Identity",
    readOnly: true,
  }),
  owner: z.string().trim().min(1).optional().meta({
    title: "Owner",
    readOnly: true,
  }),
  creator: z.string().trim().min(1).optional().meta({
    title: "Creator",
    readOnly: true,
  }),
  bot_user_id: z.string().trim().min(1).optional().meta({
    title: "Bot User ID",
    readOnly: true,
  }),
}).strict().meta({
  title: "Feishu / Lark",
  description: "Feishu or Lark Bot Resource.",
});

/** QQ Resource 完整配置 Schema。 */
const qq_resource_schema = z.object({
  id: resource_id_schema,
  type: z.literal("qq").meta({ title: "Type" }),
  name: resource_name_schema,
  app_id: z.string().trim().min(1).meta({
    title: "App ID",
    description: "QQ Bot App ID.",
  }),
  app_secret: secret_schema.meta({
    title: "App Secret",
    description: "QQ Bot App Secret.",
    writeOnly: true,
  }),
  sandbox: z.boolean().optional().meta({
    title: "Sandbox",
    description: "Whether to use the QQ sandbox environment.",
    default: false,
  }),
  identity: z.string().trim().min(1).optional().meta({
    title: "Identity",
    readOnly: true,
  }),
  bot_user_id: z.string().trim().min(1).optional().meta({
    title: "Bot User ID",
    readOnly: true,
  }),
}).strict().meta({
  title: "QQ",
  description: "QQ Bot Resource.",
});

/** Chat Plugin 单个完整 Resource Item Schema。 */
export const chat_plugin_resource_schema = z.discriminatedUnion("type", [
  telegram_resource_schema,
  feishu_resource_schema,
  qq_resource_schema,
]);

/** Chat Plugin 完整配置 Schema。 */
export const chat_plugin_config_schema = z.object({
  queue: z.object({
    max_concurrency: z.number()
      .int()
      .min(1)
      .max(32)
      .optional()
      .meta({
        title: "Maximum concurrency",
        description: "Maximum number of chat lanes executed concurrently.",
      }),
    merge_debounce_ms: z.number()
      .int()
      .min(0)
      .max(60_000)
      .optional()
      .meta({
        title: "Merge debounce",
        description: "Debounce window used to merge consecutive inbound messages.",
      }),
    merge_max_wait_ms: z.number()
      .int()
      .min(0)
      .max(120_000)
      .optional()
      .meta({
        title: "Maximum merge wait",
        description: "Maximum time to wait before executing a merged inbound burst.",
      }),
  }).strict().optional().meta({
    title: "Queue",
    description: "Chat queue scheduling and inbound message merge behavior.",
  }),
}).strict().meta({
  title: "Chat Plugin",
  description: "Chat queue behavior. Messaging channels are Plugin Resources.",
});

/** Chat Plugin 完整结构化配置。 */
export type ChatPluginConfig = z.infer<typeof chat_plugin_config_schema>;

/** 供 City Plugin Catalog 使用的标准 JSON Schema。 */
export const CHAT_PLUGIN_CONFIG_JSON_SCHEMA = z.toJSONSchema(
  chat_plugin_config_schema,
  { target: "draft-2020-12" },
) as JsonObject;

/** 供 City Plugin Catalog 使用的完整 Resource Item JSON Schema。 */
export const CHAT_PLUGIN_RESOURCE_JSON_SCHEMA = z.toJSONSchema(
  chat_plugin_resource_schema,
  { target: "draft-2020-12" },
) as JsonObject;

/** 在运行时装配边界解析并收窄 Chat Plugin 配置。 */
export function parse_chat_plugin_config(input: unknown): ChatPluginConfig {
  return chat_plugin_config_schema.parse(input);
}

/** 解析一个完整 Chat Plugin Resource Item。 */
export function parse_chat_plugin_resource(input: unknown): ChatPluginResource {
  return chat_plugin_resource_schema.parse(input);
}

/** 读取一个 Chat Resource 类型分支的标准 JSON Schema。 */
export function get_chat_plugin_resource_json_schema(
  resource_type: ChatPluginResource["type"],
): JsonObject {
  const variants = Array.isArray(CHAT_PLUGIN_RESOURCE_JSON_SCHEMA.oneOf)
    ? CHAT_PLUGIN_RESOURCE_JSON_SCHEMA.oneOf
    : [];
  for (const value of variants) {
    if (!value || typeof value !== "object" || Array.isArray(value)) continue;
    const variant = value as JsonObject;
    const properties = variant.properties;
    if (!properties || typeof properties !== "object" || Array.isArray(properties)) continue;
    const type_schema = (properties as JsonObject).type;
    if (
      type_schema
      && typeof type_schema === "object"
      && !Array.isArray(type_schema)
      && (type_schema as JsonObject).const === resource_type
    ) {
      return JSON.parse(JSON.stringify(variant)) as JsonObject;
    }
  }
  throw new Error(`Missing Chat Resource schema: ${resource_type}`);
}

/**
 * 根据用户字段解析并返回 Resolver 可写的动态字段。
 *
 * 关键点（中文）：返回值不包含 `id`、`type` 和凭据，字段所有权由 City 按 Schema 校验。
 */
export async function resolve_chat_plugin_resource(
  input: JsonObject,
): Promise<JsonObject> {
  const type = String(input.type || "").trim();
  if (type !== "telegram" && type !== "feishu" && type !== "qq") {
    throw new Error(`Unsupported Chat Resource type: ${type}`);
  }
  const result = await resolveChatChannelBotInfo({
    channel: type,
    credentials: {
      botToken: typeof input.bot_token === "string" ? input.bot_token : undefined,
      appId: typeof input.app_id === "string" ? input.app_id : undefined,
      appSecret: typeof input.app_secret === "string" ? input.app_secret : undefined,
      domain: typeof input.domain === "string" ? input.domain : undefined,
      sandbox: input.sandbox === true,
    },
  });
  const identity = String(result.identity || "").trim();
  const bot_user_id = String(result.botUserId || "").trim();
  const owner = String(result.owner || "").trim();
  const creator = String(result.creator || "").trim();
  return {
    name: result.name,
    ...(type === "telegram" && identity ? { username: identity } : {}),
    ...(type !== "telegram" && identity ? { identity } : {}),
    ...(bot_user_id ? { bot_user_id } : {}),
    ...(type === "feishu" && owner ? { owner } : {}),
    ...(type === "feishu" && creator ? { creator } : {}),
  };
}
